import {useEffect} from 'react'
import {GetServerSideProps, NextPage} from 'next'
import Head from 'next/head'

import {NewItem, Input, Select, List, PriceList} from '../components'

import { region, product, price } from '../stores'

import sty from '../styles/home.module.sass'




const NewRegion = () =>
	<NewItem name='region' store={region.edit}>
		<Input placeholder='название' edit={region.edit} fieldName='name' />
		<Input placeholder='код' edit={region.edit} fieldName='code' />
	</NewItem>



const NewProduct = () =>
	<NewItem name='product' store={product.edit}>
		<Input placeholder='название' edit={product.edit} fieldName='name' />
	</NewItem>




const NewPrice = () => {
	return <NewItem name='price' store={price.edit}>
		<Select edit={price.edit} list={region.list} fieldName='regionId' />
		<Select edit={price.edit} list={product.list} fieldName='productId' />
		<Input placeholder='название' edit={price.edit} fieldName='price' asNumber />
	</NewItem>
}




type Props = {

}


const TabButton = (p: { num, title }) => <>
	<input type='radio' id={'toggler' + p.num} name='toggler' />
	<label htmlFor={'toggler' + p.num}>{p.title}</label>
</>

const Home: NextPage<Props> = p => {
	useEffect(() => {
		Promise.all([
			region.list.fetch(),
			product.list.fetch()
		]).then(() => price.list.fetch())
	}, [])

	return <>
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app"/>
			<meta name="viewport" content="width=device-width, initial-scale=1"/>
			<link rel="icon" href="/favicon.ico"/>
		</Head>

		<main className={sty.main}>
			<div className={sty.tabs}>
				{
					['Регионы', 'Продукты', 'Цены'].map((it, i) =>
						<TabButton key={i} num={i} title={it} />
					)
				}

				<div>
					<List store={region} />
					<hr />
					<NewRegion />
				</div>
				<div>
					<List store={product} />
					<hr />
					<NewProduct />
				</div>
				<div>
					<PriceList />
					<hr />
					<NewPrice />
				</div>
			</div>
		</main>
	</>
}


export default Home


export const getServerSideProps: GetServerSideProps<Props> = async () => {

	return {
		props: {

		}
	}
}